# Generated by Django 4.2.5 on 2024-03-11 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7ed32951-c485-4ce0-a290-8f42117eda3c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
