# Generated by Django 4.2.5 on 2024-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(default="Chat", verbose_name="Имя"),
        ),
    ]
