# Generated by Django 4.2.5 on 2024-03-11 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_user_id_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7e554967-eaf7-4692-a46e-dbd2e4aa12f6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
