# Generated by Django 4.2.5 on 2024-05-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="name",
        ),
    ]
