# Generated by Django 5.0.3 on 2024-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_chat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_filename",
            field=models.CharField(blank=True),
        ),
    ]
