# Generated by Django 4.2.5 on 2024-03-11 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0c2d36b6-a518-43cc-beae-20eddbecf819"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
