# Generated by Django 4.2.5 on 2024-03-11 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("fb050589-b131-4a00-8eb9-0ce5e296ff40"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
