# Generated by Django 4.2.5 on 2024-03-11 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("6c592c28-291b-43cd-a9e4-abdfce0e29eb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
