# Generated by Django 4.2.5 on 2024-03-11 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("e3e9ca30-cfd8-43a5-b3c6-63455e5e2727"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
